#加载application-datasource
spring:
  profiles:
    active: datasource
  servlet:
    multipart:
      enabled: true       #开启文件上传
      max-file-size: 20MB #限制文件上传大小

#端口
server:
  port: 8002

#mybatis
mybatis:
  type-aliases-package: com.cjj.qlemusic.security.entity,com.cjj.qlemusic.admin.dto
#加载mybatis映射文件
  mapper-locations:
    - classpath:mapper/*Mapper.xml
    - classpath:securityMapper/*Mapper.xml

#redis自定义key
redis:
   database: qlemusic
   key:
      admin: ':ums:admin:'
      resourceList: 'ums:resourceList'
   expire:
      common: 86400 # 24小时

#shiro
shiro:
  loginUrl: /
  unauthorizedUrl: /admin/unauthorized
  realm:
    cachingEnabled: true
    authenticationCachingEnabled: true
    authorizationCachingEnabled: true
  credentialsMatcher:
    algorithm: MD5
    iteration: 2
    hexEncoded: true
  filterKey:
    url: url
    permission: permission
  lists:
  - url: /**.html
    permission: anon
  - url: /admin/test3
    permission: anon
  - url: /admin/login
    permission: anon
  - url: /**
    permission: jwtFilter

#JWT
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secretKey: qiuqiaofang     #JWT加解密使用的秘钥
  expiration: 86400          #JwtToken过期时间(7天604800)
  tokenHead: Bearer          #JWT负载中拿到开头

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test                         # 访问身份验证中用到用户标识
    accessKeySecret: test                     # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: qlemusic-oss1                 # oss的存储空间
    policy:
      expire: 100 # 签名有效期(S)
    maxSize: 10                                         # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: qlemusic/images/ # 上传文件夹路径前缀
