#加载环境
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true       #开启文件上传
      max-file-size: 20MB #限制文件上传大小
      max-request-size: 20MB #限制请求上传大小

#端口
server:
  port: 8001

#mybatis
mybatis:
  type-aliases-package: com.cjj.qlemusic.security.entity,com.cjj.qlemusic.portal.entity
#加载mybatis映射文件
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:securityMapper/*.xml

#redis自定义key（用户）
redis:
   database: qlemusic
   key:
      admin: ':ums:user:'
      prefixId: ':userId:'
      resourceList: 'ums:resourceList'
      verify: ':verify:'
      userVisitCount: ':ums:visit:count:'
      userLike: ':like:user:'
      likedCount: ':like:count:'
      userComment: ':comment:user:'
      replyUserComment: ':comment:replyuser:'
      commentedCount: ':comment:count:'
      userInfoToComment: ':comment:userinfo:'
      playedCount: ':play:count:'
   expire:
      common: 86400   # 24小时
      verify: 120     # 2分钟


#用户信息
user:
  avatar: https://qlmusic-oss1.oss-cn-zhangjiakou.aliyuncs.com/qlemusic/images/default/default-avatar.png # 默认头像地址
  uniqueId: eiqle
  telLoginType: phone
  qqLoginType: qq
  wxLoginType: wx
  credentialVerifyType: verify
  credentialPasswordType: password

#shiro
shiro:
  loginUrl: /
  unauthorizedUrl: /admin/unauthorized
  realm:
    cachingEnabled: true
    authenticationCachingEnabled: true
    authorizationCachingEnabled: true
  credentialsMatcher:
    algorithm: MD5
    iteration: 2
    hexEncoded: true
  filterKey:
    url: url
    permission: permission
  lists:
  - url: /**.html
    permission: anon
  - url: /admin/test3
    permission: anon
  - url: /admin/login
    permission: anon
  - url: /oauth/**
    permission: anon
  - url: /user/telRegister
    permission: anon
  - url: /user/matchVerify
    permission: anon
  - url: /user/sendSms
    permission: anon
  - url: /user/login
    permission: anon
  - url: /user/getUserById
    permission: anon
  - url: /visit/**
    permission: anon
  - url: /play/**
    permission: anon
  - url: /comment/getCommentByMusic
    permission: anon
  - url: /comment/getUserByComment
    permission: anon
  - url: /audio/**
    permission: anon
  - url: /**
    permission: jwtFilter

#JWT
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secretKey: qiuqiaofang     #JWT加解密使用的秘钥
  expiration: 86400          #JwtToken过期时间(7天604800)
  tokenHead: Bearer          #JWT负载中拿到开头

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com           # oss对外服务的访问域名
    accessKeyId: LTAI4G2AFrqNjveyrrXFpjMA               # 访问身份验证中用到用户标识
    accessKeySecret: N8uK0lnQ60yeD7Hhp2DPvz1Gyn8vn7     # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    host: http://qlmusic-oss1.oss-cn-zhangjiakou.aliyuncs.com/
    bucketName: qlmusic-oss1                            # oss的存储空间
    policy:
      expire: 100 # 签名有效期(S)
    maxSize: 10                                         # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: qlemusic/images/ # 上传文件夹路径前缀
      audiosPrefix: qlemusic/audios/ # 上传文件夹路径前缀

# 阿里云短信
aliyuncs:
  type:
    sendSms: SendSms                # 发短信
  sendSms:
    regionId: cn-hangzhou           # 地区
    signName: qlmusic               # 签名名称
    templateCode: SMS_205070324    # 模板ID（CODE）
    endpoint: dysmsapi.aliyuncs.com # 服务地址
    version: 2017-05-25             # 版本号
    verifyKey: code                 # 验证码Key
    parameters:
      regionIdKey: RegionId
      phoneNumbersKey: PhoneNumbers
      signNameKey: SignName
      templateCodeKey: TemplateCode
      templateParamKey: TemplateParam

# 消息队列rabbitMQ
rabbitmq:
  queue:
    name:
      msgTip: msgTipQueue